name = "system-assets"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# OpenNext Cloudflare adapter output
main = ".open-next/worker.js"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "system-assets-db"
database_id = "9b5674d3-c3ae-4121-bfc4-fd5c928a39ad"
migrations_dir = "d1/migrations"
